name: "generate-snake-game-from-github-contribution-grid"
description: "Generates a snake game from a github user contributions grid. Output the animation as gif or svg"
author: "platane"

runs:
  using: docker
  image: docker://platane/snk:sha256:a8082dd35baa9da91c686c7a7f25eb4f7216f5ab0cafe8cdec486994539bbe9d

inputs:
  github_user_name:
    description: "github user name"
    required: true
  gif_out_path:
    description: "path of the generated gif file. If left empty, the gif file will not be generated."
    required: false
    default: null
  svg_out_path:
    description: "path of the generated svg file. If left empty, the svg file will not be generated."
    required: false
    default: null

outputs:
  gif_out_path:
    description: "path of the generated gif"
  svg_out_path:
    description: "path of the generated svg"
