name: "generate-snake-game-from-github-contribution-grid"
description: "Generates a snake game from a github user contributions grid and output a screen capture as gif"
author: "platane"

outputs:
  gif_out_path:
    description: "path of the generated gif"
  svg_out_path:
    description: "path of the generated svg"

runs:
  using: "docker"
  image: "docker://platane/snk:latest"

inputs:
  github_user_name:
    description: "github user name"
    required: true
  gif_out_path:
    description: "path of the generated gif"
    required: false
    default: null
  svg_out_path:
    description: "path of the generated svg"
    required: false
    default: null
