name: "generate-snake-game-from-github-contribution-grid"
description: "Generates a snake game from a github user contributions grid. Output the animation as gif or svg"
author: "platane"

runs:
  using: docker
  image: docker://platane/snk@sha256:767615f6d5cc39228b8adb364346ab585821020eb604ab353a5f55edb90bf2d0

inputs:
  github_user_name:
    description: "github user name"
    required: true
  gif_out_path:
    description: "path of the generated gif file. If left empty, the gif file will not be generated."
    required: false
    default: null
  svg_out_path:
    description: "path of the generated svg file. If left empty, the svg file will not be generated."
    required: false
    default: null

outputs:
  gif_out_path:
    description: "path of the generated gif"
  svg_out_path:
    description: "path of the generated svg"
