name: "generate-snake-game-from-github-contribution-grid"
description: "Generates a snake game from a github user contributions grid and output a screen capture as gif"
author: "platane"

outputs:
  gif_out_path:
    description: "path of the generated gif"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.github_user_name }}
    - ${{ inputs.gif_out_path }}

inputs:
  github_user_name:
    description: "github user name"
    required: true
  gif_out_path:
    description: "path of the generated gif"
    required: false
    default: "./github-contribution-grid-snake.gif"
