name: "generate-snake-game-from-github-contribution-grid"
description: "Generates a snake game from a github user contributions grid. Output the animation as svg"
author: "platane"

runs:
  using: node16
  main: index.js

inputs:
  github_user_name:
    description: "github user name"
    required: true
  svg_out_path:
    description: "path of the generated svg file. If left empty, the svg file will not be generated."
    required: false
    default: null

outputs:
  svg_out_path:
    description: "path of the generated svg"
