name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: 14

      - uses: bahmutov/npm-install@v1.4.1

      - run: yarn build:demo
        env:
          BASE_PATHNAME: "snk"

      - uses: crazy-max/ghaction-github-pages@068e494
        with:
          target_branch: gh-pages
          build_dir: packages/demo/dist
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN_GH_PAGES }}
